### PR TITLE
Use Ubuntu 20.04 and point to new ppa for complx and nin10kit

### PR DESCRIPTION
**Pull request by TricksterGuy**
See #1 as this removes the gba-linker-script package since its not in a ppa, and due to the 20.04 switch won't have a package for it.

Also not mentioned in the commit log, I've added gdb-multiarch for GBA debugging.

For visibility: I've also made the switch to 20.04, since the pyLC3 stuff [**will not work**](https://github.com/TricksterGuy/pylc3-examples/runs/1629233529?check_suite_focus=true) on bionic for some reason that I don't care to debug.

### CODE REVIEW

**Comment by TricksterGuy** [comment]
Added a PDF viewer as well.

**Comment by kanwren** [comment]
These commits are already on master, excluding the merge commit. Was this intentional?

The build fails during the CircuitSim install:

```
E: Version '8u161-b12-1ubuntu2' for 'openjfx' was not found
E: Version '8u161-b12-1ubuntu2' for 'libopenjfx-java' was not found
E: Version '8u161-b12-1ubuntu2' for 'libopenjfx-jni' was not found
```

[Possible relevant question on SO](https://stackoverflow.com/questions/61783369/install-openjdkopenjfx-8-on-ubuntu-20)

**Comment by TricksterGuy** [comment]
yeah ftr whoops thought I committed to a fork. 

I'm not certain what version of those libs CircuitSim needs, but just sudo apt install openjfx should fix it IDK why its pinned to a specific version.

**Comment by kanwren** [comment]
I'm unpinning it for now, but this is probably not an ideal solution. Java versions are often very sensitive and this might break in the future.

**Pull request closed without merging**
