### PR TITLE
Replace mednafen with mgba.

### PR DESCRIPTION
**Pull request by TricksterGuy**
So here's the official pull request, to get rid of mednafen as the 2110 emulator.

A little history lesson FTR.
----

We used to use Visualboyadvance-M for GBA emulation, we didn't have a problem with that (using Dualbooting / Virtual Machines), and during my time I had a fork of this emulator that did allow printf to work (with some hackery in the Makefiles).

As soon as I left mednafen was added (and I don't recall exactly why the TA just said this was more accurate). 

Docker was introduced and as I can tell from the commits it was found out that vbam ran super fast and mednafen did not, so vbam was dropped. The reason for the super fastness of vbam is due to there being no sound card in Docker. Most emulators use sound as a way to "sync" between frames, since there's no sound card there's nothing to keep in sync with. Mednafen worked because it probably sync'd with video instead of audio, I don't feel like digging deeper into that so that's my theory.

The issues with mednafen
---

Mednafen is a multi-system emulator, and is more geared towards being a one program solution to emulating multiple systems. overkill for just doing GBA development.

so in short here's the issues with this emulator we have seen over the past couple of semesters.

1. A crash that students can trigger when functions utilizing DMA are coded incorrectly (big DMAs in a loop to where it lasts longer than a VBlank).
2. Since it is a multi system emulator it is not focused on GBA development, and since its based off older VisualBoyAdvance (and not VBA-M) it isn't the most accurate GBA emulator
3. No debugging functionality at all. An actual GBA emulators would have at least a memory viewer, hardware register viewer, sprite/tile/map viewer, and GDB support. Since mednafen is geared towards multi-system emulation and just playing games it doesn't have such features. Its not geared towards development.

Motivation for MGBA
----

1. Mature GBA emulator, has seen a lot of use over VisualBoyAdvance(-M) and is actively developed.
2. Fast and boasts that it's the most accurate GBA emulator.
3. Support for debugging with gdb
4. Memory viewer, Sprite Viewer etc (Potentially useful during lecture I guess)
5. Other nice things like (Frame Inspector - should be able to catch tearing with this, being able to record a gif for potential student problems, etc).

### CODE REVIEW

**Comment by TricksterGuy** [comment]
Also if the current Makefiles are given to me I can update them for this.

But it should just be simply replacing mednafen with mgba-qt.

However I would like to have the Makefile so that I could add targets for connecting mgba with gdb.

**Comment by TricksterGuy** [comment]
Update here's the targets I came up with.


```
debug : CFLAGS += $(CDEBUG) -I../shared
debug : LDFLAGS += $(LDDEBUG)
debug : $(PROGNAME).gba
	@echo "[FINISH] Created $(PROGNAME).gba"

gdb : debug
	@echo "[EXECUTE] Running Emulator MGBA with GDB, see emulator.log if the command fails"
	@mgba-qt $(PROGNAME).gba --gdb &
	# To give mgba some time to initialize and start up the GDB server.
	@sleep 0.5
	@gdb-multiarch -ex 'file $(PROGNAME).elf' -ex 'target remote 127.0.0.1:2345'

.PHONY : mgba
mgba : CFLAGS += $(CRELEASE) -I../shared
mgba : LDFLAGS += $(LDRELEASE)
mgba : $(PROGNAME).gba
	@echo "[EXECUTE] Running Emulator MGBA, see emulator.log if the command fails"
	@mgba-qt $(PROGNAME).gba
```

**Comment by TricksterGuy** [comment]
Worth nothing that latest mgba version is now 0.9.2

Seems that some changes (bug fixes) were made to the qt version that may be helpful.

I can append to this pull request or you can take it from here.

**Comment by kanwren** [comment]
If you know where to find it, that would be helpful. I wish we didn't have to keep the deb files in the repo, though :sweat_smile:

**Comment by TricksterGuy** [comment]
https://github.com/mgba-emu/mgba/releases/tag/0.9.2

Unfortunately not distributed in package manager (or if it is a really old version)

**Comment by kanwren** [comment]
Thanks! I'll bump it in the morning.

My meaning was that `wget`ing them or equivalent may be more convenient and consistent, though it's probably better in the long run to leave it the way it is in this case.

**Comment by TricksterGuy** [comment]
Any updates on this :^)

**Comment by kanwren** [comment]
Version is bumped, but semantics in GitHub CI scripts changed, stand by for fix :p

We're looking at the GBA makefiles later this week.

**Comment by kanwren** [comment]
I took a look and it was pretty trivial to migrate the Makefiles, as you said. All the Makefiles for the GBA homework have been updated. The gdb integration works great.

**Pull request merged**
